/* This file is generated by make_achievements.sh */
using UnityEngine;
using System.Collections;
using GooglePlayGames;
using UnityEngine.SocialPlatforms;

public  class AchievementsList {

// Yes the default value is false, http://msdn.microsoft.com/en-us/library/c8f5xwh7.aspx
private bool[] executed = new bool[6];

	public void GetUnityWorks() {
		if (!executed[0]) {
			Social.ReportProgress ("CgkIj8PyxKwKEAIQAg", 100.0f, (bool success) => {
				// handle success or failure
			});
			executed[0] = true;
		}
	}
	
	public void GetRan10Meters() {
		if (!executed[1]) {
			Social.ReportProgress ("CgkIj8PyxKwKEAIQAw", 100.0f, (bool success) => {
				// handle success or failure
			});
			executed[1] = true;
		}
	}
	
	public void GetRan20Meters() {
		if (!executed[2]) {
			Social.ReportProgress ("CgkIj8PyxKwKEAIQBA", 100.0f, (bool success) => {
				// handle success or failure
			});
			executed[2] = true;
		}
	}
	
	public void GetRan30Meters() {
		if (!executed[3]) {
			Social.ReportProgress ("CgkIj8PyxKwKEAIQBQ", 100.0f, (bool success) => {
				// handle success or failure
			});
			executed[3] = true;
		}
	}
	
	public void GetRan40Meters() {
		if (!executed[4]) {
			Social.ReportProgress ("CgkIj8PyxKwKEAIQBg", 100.0f, (bool success) => {
				// handle success or failure
			});
			executed[4] = true;
		}
	}
	
	public void GetRan50Meters() {
		if (!executed[5]) {
			Social.ReportProgress ("CgkIj8PyxKwKEAIQBw", 100.0f, (bool success) => {
				// handle success or failure
			});
			executed[5] = true;
		}
	}
	
}
